version: '3.4'

services:
  xmlnamevalidator:
    image: xmlnamevalidator
    build:
      context: node_modules/xml-name-validator
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
